name: URL Shortcut CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # specify your Ruby version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            --data '{"clearCache": "do_not_clear"}' \
            https://api.render.com/v1/services/srv-cq59e308fa8c7383kr9g/deploys
